# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: testing

on:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test-flutter:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.16.0
        with:
          channel: 'stable'

      - name: Build generated classes
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze project source
        run: flutter analyze --no-fatal-infos

      - name: Run tests
        run: flutter test --coverage